#!/bin/bash

# Requires access to system python
cd ${0%/*}
python -m venv venv
source venv/bin/activate
python -m ensurepip --upgrade

# Install dependancies
pip install flask
pip install esphome
pip install yamldb
pip install cloudmesh-common
