---
http:
  host: "0.0.0.0"  
  port: 8080
system:
  bin:  bin
  data: data
  repos:   data/repos
  devices: data/devices
  units:   data/units

commands:
  - name: status
    command: bin/esp-status.py 
        
