---
system:
  bin:  bin
  data: data
  tools:
    - name: esphome
      environment:
        VIRTUAL_ENV: "../esphome/venv"
        PATH: "$VIRTUAL_ENV/bin"
    - name: esptool.py
  devices: devices

devices:
  - name: demo
    tasks:
      - name: query
        task: esp-status.py
        
